// Mock product data — replaced with real API in Phase 24
export const MOCK_PRODUCTS = [
  {
    _id: '1',
    name: 'VŌGN Classic Cap',
    slug: 'vogn-classic-cap',
    category: 'caps',
    price: 12000,
    discountPrice: 9500,
    images: ['https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=600&q=80'],
    colors: ['#1a1a1a', '#F7E1D7', '#4A5759'],
    sizes: ['S', 'M', 'L'],
    isFeatured: true,
    isBestseller: true,
    badge: 'Bestseller',
  },
  {
    _id: '2',
    name: 'Iron Street Tee',
    slug: 'iron-street-tee',
    category: 't-shirts',
    price: 15000,
    discountPrice: null,
    images: ['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600&q=80'],
    colors: ['#1a1a1a', '#ffffff', '#4A5759'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    isFeatured: true,
    isBestseller: false,
    badge: 'New',
  },
  {
    _id: '3',
    name: 'Ash Pullover Hoodie',
    slug: 'ash-pullover-hoodie',
    category: 'hoodies',
    price: 28000,
    discountPrice: 22000,
    images: ['https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=600&q=80'],
    colors: ['#B0C4B1', '#1a1a1a', '#DEDBD2'],
    sizes: ['S', 'M', 'L', 'XL'],
    isFeatured: true,
    isBestseller: true,
    badge: 'Sale',
  },
  {
    _id: '4',
    name: 'Lagos Tote Bag',
    slug: 'lagos-tote-bag',
    category: 'bags',
    price: 18000,
    discountPrice: null,
    images: ['https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&q=80'],
    colors: ['#1a1a1a', '#F7E1D7'],
    sizes: ['One Size'],
    isFeatured: true,
    isBestseller: false,
    badge: null,
  },
  {
    _id: '5',
    name: 'Dust Cargo Jacket',
    slug: 'dust-cargo-jacket',
    category: 'jackets',
    price: 45000,
    discountPrice: 38000,
    images: ['https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&q=80'],
    colors: ['#DEDBD2', '#4A5759', '#1a1a1a'],
    sizes: ['S', 'M', 'L', 'XL'],
    isFeatured: true,
    isBestseller: true,
    badge: 'Sale',
  },
  {
    _id: '6',
    name: 'Petal Silk Scarf',
    slug: 'petal-silk-scarf',
    category: 'accessories',
    price: 8500,
    discountPrice: null,
    images: ['https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=600&q=80'],
    colors: ['#F7E1D7', '#B0C4B1'],
    sizes: ['One Size'],
    isFeatured: false,
    isBestseller: true,
    badge: 'New',
  },
  {
    _id: '7',
    name: 'Urban Snapback',
    slug: 'urban-snapback',
    category: 'caps',
    price: 10000,
    discountPrice: 8000,
    images: ['https://images.unsplash.com/photo-1575428652377-a2d80e2277fc?w=600&q=80'],
    colors: ['#1a1a1a', '#4A5759'],
    sizes: ['One Size'],
    isFeatured: false,
    isBestseller: true,
    badge: 'Sale',
  },
  {
    _id: '8',
    name: 'Oversized Drop Tee',
    slug: 'oversized-drop-tee',
    category: 't-shirts',
    price: 18000,
    discountPrice: null,
    images: ['https://images.unsplash.com/photo-1503341504253-dff4815485f1?w=600&q=80'],
    colors: ['#ffffff', '#1a1a1a', '#B0C4B1'],
    sizes: ['M', 'L', 'XL', 'XXL'],
    isFeatured: false,
    isBestseller: true,
    badge: null,
  },
];

export const FEATURED_PRODUCTS  = MOCK_PRODUCTS.filter(p => p.isFeatured);
export const BESTSELLER_PRODUCTS = MOCK_PRODUCTS.filter(p => p.isBestseller);
